// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClothingWebStore.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public string UserId { get; set; }

    public DateTime OrderDate { get; set; }

    public int BillingAddressId { get; set; }

    public int ShippingAddressId { get; set; }

    public decimal TotalPrice { get; set; }

    public decimal Vat { get; set; }

    public virtual Address BillingAddress { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Address ShippingAddress { get; set; }

    public virtual AspNetUser User { get; set; }
}